image: golang:1.10

stages:
  - test

variables:
  PROJECT_SRC_DIR: "${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}"

before_script:
  # Ensure a symlink to ${CI_PROJECT_DIR} exists before installing
  - mkdir -p "${PROJECT_SRC_DIR}"
  - ln -s "${CI_PROJECT_DIR}" "${PROJECT_SRC_DIR}/${CI_PROJECT_NAME}"
  # install dependencies
  - go get -v ./...
  - go get -v golang.org/x/tools/cmd/goimports
  - go get -v gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install

testing:
  stage: test
  script:
    - diff <(goimports -d .) <(echo -n)
    - go test -v -race ./...
    - gometalinter.v2 ./... --deadline 15m
