image: golang:1.10

stages:
  - build
  - compile
  - test
  - stage
  - deploy

variables:
  TF_IMAGE: hashicorp/terraform:0.11.7
  TF_BACKEND_S3_KEY: lambda/pong
  TF_PLANFILE: "${CI_PROJECT_DIR}/.deployment/${CI_PIPELINE_ID}.tfplan"
  GO_ARTIFACT: "${CI_PROJECT_DIR}/.deployment/pong"
  DOCKER_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}"

Docker Build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - >
      docker login
      --username "${CI_REGISTRY_USER}"
      --password "${CI_REGISTRY_PASSWORD}"
      "${CI_REGISTRY}"
  script:
    - docker pull "${DOCKER_IMAGE}" || true
    - >
      docker build
      --tag "${DOCKER_IMAGE}"
      --cache-from "${DOCKER_IMAGE}"
      "${CI_PROJECT_DIR}"
    - docker push "${DOCKER_IMAGE}"

Go Build:
  stage: compile
  image: "${DOCKER_IMAGE}"
  script:
    - go build -v -o "${GO_ARTIFACT}"
  artifacts:
    paths:
      - "${GO_ARTIFACT}"
    expire_in: 30 days
  retry: 1

Go Tests:
  image: "${DOCKER_IMAGE}"
  stage: test
  script:
    # install linters
    - >
      go get -v
      golang.org/x/tools/cmd/goimports
      gopkg.in/alecthomas/gometalinter.v2
    - gometalinter.v2 --install
    - diff <(goimports -d .) <(echo -n)
    - go test -v -race "$(go list ./... | grep -v /vendor/)"
    - >
      gometalinter.v2
      --deadline 50m
      --concurrency=2
      --vendor
      --exclude=^vendor\/
      ./...
  except:
    - master
    - gitlab-ci
  dependencies: []
  retry: 1

Terraform Plan:
  stage: stage
  image:
    name: ${TF_IMAGE}
    entrypoint: ["/usr/bin/env"]
  before_script:
    - cd .deployment
    - terraform init -backend-config="key=${TF_BACKEND_S3_KEY}"
  script:
    - terraform plan -out="${TF_PLANFILE}"
  artifacts:
    paths:
      - "${TF_PLANFILE}"
    expire_in: 30 days
  dependencies:
    - "Go Build"
  retry: 1

Terraform Apply:
  stage: deploy
  image:
    name: ${TF_IMAGE}
    entrypoint: ["/usr/bin/env"]
  before_script:
    - cd .deployment
    - terraform init -backend-config="key=${TF_BACKEND_S3_KEY}"
  script:
    - terraform apply "${TF_PLANFILE}"
  only:
    - gitlab-ci
  dependencies:
    - "Go Build"
    - "Terraform Plan"
  artifacts:
    paths:
      - .deployment
    expire_in: 2 weeks
    when: on_failure
