image: golang:1.10

stages:
  - build
  - test
  - stage
  - deploy

variables:
  TF_IMAGE: hashicorp/terraform:0.11.7
  TF_BACKEND_S3_KEY: lambda/pong
  TF_PLANFILE: "${CI_PROJECT_DIR}/.deployment/${CI_PIPELINE_ID}.tfplan"
  GO_ARTIFACT: "${CI_PROJECT_DIR}/.deployment/pong"

before_script:
  # Some variables we'll need...
  - >
    NAMESPACE_SRC_DIR="${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}"
    PROJECT_SRC_DIR="${NAMESPACE_SRC_DIR}/${CI_PROJECT_NAME}"

  # Ensure a symlink to this project directory exists within GOPATH
  - mkdir -p "${NAMESPACE_SRC_DIR}"
  - ln -s "${CI_PROJECT_DIR}" "${PROJECT_SRC_DIR}"
  - cd "${PROJECT_SRC_DIR}"

  # install go dependencies
  # discordgo develop branch
  - >
    (
      go get -v github.com/bwmarrin/discordgo
      cd ${GOPATH}/src/github.com/bwmarrin/discordgo
      git checkout develop
    )

  # all other dependencies
  - go get -v ./...

Go Build:
  script:
    - go build -o "${GO_ARTIFACT}"
  artifacts:
    paths:
      - "${GO_ARTIFACT}"
    expire_in: 30 days
  retry: 1

Go Tests:
  stage: test
  script:
    # install linters
    - >
      go get -v
      golang.org/x/tools/cmd/goimports
      gopkg.in/alecthomas/gometalinter.v2
    - gometalinter.v2 --install
    - diff <(goimports -d .) <(echo -n)
    - go test -v -race "$(go list ./... | grep -v /vendor/)"
    - >
      gometalinter.v2
      --deadline 50m
      --concurrency=2
      --vendor
      --exclude=^vendor\/
      ./...
  except:
    - master
    - gitlab-ci
  dependencies: []
  retry: 1

Terraform Plan:
  stage: stage
  image:
    name: ${TF_IMAGE}
    entrypoint: ["/usr/bin/env"]
  before_script:
    - cd .deployment
    - terraform init -backend-config="key=${TF_BACKEND_S3_KEY}"
  script:
    - terraform plan -out="${TF_PLANFILE}"
  artifacts:
    paths:
      - "${TF_PLANFILE}"
    expire_in: 30 days
  dependencies:
    - "Go Build"
  retry: 1

Terraform Apply:
  stage: deploy
  image:
    name: ${TF_IMAGE}
    entrypoint: ["/usr/bin/env"]
  before_script:
    - cd .deployment
    - terraform init -backend-config="key=${TF_BACKEND_S3_KEY}"
  script:
    - terraform apply "${TF_PLANFILE}"
  only:
    - gitlab-ci
  dependencies:
    - "Go Build"
    - "Terraform Plan"
