image: golang:1.10

stages:
  - test

before_script:
  # Some variables we'll need...
  - >
    NAMESPACE_SRC_DIR="${GOPATH}/src/gitlab.com/${CI_PROJECT_NAMESPACE}"
    PROJECT_SRC_DIR="${NAMESPACE_SRC_DIR}/${CI_PROJECT_NAME}"

  # Ensure a symlink to this project directory exists within GOPATH
  - mkdir -p "${NAMESPACE_SRC_DIR}"
  - ln -s "${CI_PROJECT_DIR}" "${PROJECT_SRC_DIR}"
  - cd "${PROJECT_SRC_DIR}"

  # install go dependencies
  # discordgo develop branch
  - >
    (
      go get -v github.com/bwmarrin/discordgo
      cd ${GOPATH}/src/github.com/bwmarrin/discordgo
      git checkout develop
    )

  # all other dependencies
  - go get -v ./...
  # install linters
  - >
    go get -v
    golang.org/x/tools/cmd/goimports
    gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install

Terraform Plan:
  image:
    name: hashicorp/terraform:0.11.7
    entrypoint: ["/usr/bin/env"]
  stage: test
  before_script:
    - cd .deployment
    - terraform init -backend-config="key=lambda/pong"
  script:
    - terraform plan
  retry: 1

Go Tests:
  stage: test
  script:
    - diff <(goimports -d .) <(echo -n)
    - go test -v -race "$(go list ./... | grep -v /vendor/)"
    - >
      gometalinter.v2
      --deadline 50m
      --concurrency=2
      --vendor
      --exclude=^vendor\/
      ./...
  except:
    - master
  retry: 1
